; IBARRA HERNANDEZ JEANELY FERNANDA - LCD01.asm
.MODEL SMALL                       
.STACK
.DATA  
    MENSAJE DB 'HOLA MUNDO LCD' ; LONG 14
.CODE
    MOV AX,@DATA
    MOV DS, AX
    
    MOV SI,0     ; INDICE
    MOV CX,14 
    MOV DX,2040H ; PUERTO INICIAL DE LCD
    
LABEL01:  
    MOV AL,MENSAJE[SI]
    OUT DX,AL    ; ENVIAR HACIA EL PUERTO DEL CONTENIDO DE <AL>
    INC SI
    INC DX
    LOOP LABEL01         
    
    MOV AX,4C00H
    INT 21H  
 END