/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jeane
 */
public class FrameCuadruplos extends javax.swing.JFrame {    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameCuadruplos.class.getName());
    String tresDirecciones = "";    
    
    /**
     * Creates new form NewJFrame
     */
    public FrameCuadruplos() {
        initComponents();
        setLocationRelativeTo(null);
        tblCuadruplos.getTableHeader().setFont(new java.awt.Font("Seoge UI", java.awt.Font.BOLD, 24));
        tblCuadruplos.getTableHeader().setPreferredSize(new Dimension(tblCuadruplos.getTableHeader().getPreferredSize().height,50));     
        DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
            centro.setHorizontalAlignment(SwingConstants.CENTER);

            for (int i = 0; i < tblCuadruplos.getColumnCount(); i++) {
                tblCuadruplos.getColumnModel().getColumn(i).setCellRenderer(centro);
            }
            
        ((DefaultTableCellRenderer) tblCuadruplos.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    public FrameCuadruplos(Nodo arbolExpresion) {
        initComponents();
        setLocationRelativeTo(null);
        tblCuadruplos.getTableHeader().setFont(new java.awt.Font("Seoge UI", java.awt.Font.BOLD, 24));
        tblCuadruplos.getTableHeader().setPreferredSize(new Dimension(tblCuadruplos.getTableHeader().getPreferredSize().height,50));     
        DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
        centro.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblCuadruplos.getColumnCount(); i++) {
            tblCuadruplos.getColumnModel().getColumn(i).setCellRenderer(centro);
        }
        
        tresDirecciones = arbolExpresion.getCodigoIntermedio();
        generarCuadruplos();
    }
    
    private void generarCuadruplos() {
        DefaultTableModel modelo = (DefaultTableModel) tblCuadruplos.getModel();
        modelo.setRowCount(0);
        
        String operador;
        String arg1;
        String arg2;
        String resultado;

        String[] lineas = tresDirecciones.split("\n");
        int contador = 0;

        for(int i=0;i<lineas.length;i++){
            String linea=lineas[i];
            linea = linea.trim();
            
            if (linea.isEmpty()) continue;

            operador = "";
            arg1 = "";
            arg2 = "";
            resultado = "";

            String[] elem = linea.split("=");
            if (elem.length != 2) continue;

            resultado = elem[0].trim();

            String expresion = elem[1].trim();
            if (expresion.contains("+")) {
                operador = "+";
                String[] operandos = expresion.split("\\+");
                arg1 = operandos[0].trim();
                arg2 = operandos[1].trim();

            } else if (expresion.contains("-")) {
                operador = "-";
                String[] operandos = expresion.split("-");
                arg1 = operandos[0].trim();
                arg2 = operandos[1].trim();

            } else if (expresion.contains("*")) {
                operador = "*";
                String[] operandos = expresion.split("\\*");
                arg1 = operandos[0].trim();
                arg2 = operandos[1].trim();

            } else if (expresion.contains("/")) {
                operador = "/";
                String[] operandos = expresion.split("/");
                arg1 = operandos[0].trim();
                arg2 = operandos[1].trim();

            } else if (expresion.contains("^")) {
                operador = "^";
                String[] operandos = expresion.split("\\^");
                arg1 = operandos[0].trim();
                arg2 = operandos[1].trim();

            } else {
                operador = "=";
                arg1 = expresion;
            }

            modelo.addRow(new Object[]{
                contador++,
                operador,
                arg1,
                arg2,
                resultado
            });
        }
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuadruplos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(62, 59, 59));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Cuádruplos - LyA2");
        jLabel8.setToolTipText("");
        jLabel8.setMaximumSize(new java.awt.Dimension(30, 32));
        jLabel8.setPreferredSize(new java.awt.Dimension(5, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(62, 59, 59));

        btnSalir.setBackground(new java.awt.Color(253, 250, 250));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setPreferredSize(new java.awt.Dimension(20, 39));
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(642, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tblCuadruplos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblCuadruplos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "op", "arg1", "arg2", "resultado"
            }
        ));
        tblCuadruplos.setEnabled(false);
        tblCuadruplos.setRowHeight(50);
        tblCuadruplos.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tblCuadruplos);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameCuadruplos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCuadruplos;
    // End of variables declaration//GEN-END:variables
}
